name: trade_producer
language: python
variables:
  - name: OHLC_WINDOWS_SECONDS
    inputType: FreeText
    multiline: false
    defaultValue: 60
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    multiline: false
    defaultValue: live
    required: true
  - name: LAST_N_DAYS
    inputType: FreeText
    multiline: false
    defaultValue: 90
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    multiline: false
    defaultValue: trade
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
