name: trade_producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    multiline: false
    defaultValue: trade
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
