name: price_predictor
language: python
variables:
  - name: FEATURE_VIEW_NAME
    inputType: FreeText
    multiline: false
    defaultValue: ohlc_feature_view
  - name: FEATURE_VIEW_VERSION
    inputType: FreeText
    multiline: false
    defaultValue: 1
  - name: FEATURE_GROUP_NAME
    inputType: FreeText
    multiline: false
    defaultValue: ohlc_feature_group
  - name: FEATURE_GROUP_VERSION
    inputType: FreeText
    multiline: false
    defaultValue: 1
  - name: LAST_N_MINUTES
    inputType: FreeText
    multiline: false
    defaultValue: 10
  - name: OHLC_WINDOW_SEC
    inputType: FreeText
    multiline: false
    defaultValue: 60
  - name: COMET_API_KEY
    inputType: FreeText
    multiline: false
    defaultValue: hxEjTuG2oq86BVOjyihkHTH31
  - name: COMET_PROJECT_NAME
    inputType: FreeText
    multiline: false
    defaultValue: real-time-ohlc
  - name: COMET_WORKSPACE
    inputType: FreeText
    multiline: false
    defaultValue: sebastian-ospina
  - name: HOPSWORKS_PROJECT_NAME
    inputType: FreeText
    multiline: false
    defaultValue: testone
  - name: HOPSWORKS_API_KEY
    inputType: FreeText
    multiline: false
    defaultValue: jJ3EIJAs48fiyY7p.x6b3cmLBwWldeqRZRe0yLfPdCzwcvm9gyEow6jgLY7QbskO4nIov6JuZFsT7ndEp
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
