name: trade_to_ohlc
language: python
variables:
  - name: KAFKA_INPUT_TOPIC
    inputType: InputTopic
    multiline: false
    defaultValue: trade
    required: true
  - name: KAFKA_OUTPUT_TOPIC
    inputType: OutputTopic
    multiline: false
    defaultValue: ohlc
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
