name: trade_to_ohlc
language: python
variables:
  - name: KAFKA_INPUT_TOPIC
    inputType: InputTopic
    multiline: false
    defaultValue: trade
    required: true
  - name: KAFKA_OUTPUT_TOPIC
    inputType: OutputTopic
    multiline: false
    defaultValue: ohlc
    required: true
  - name: KAFKA_FEATURE_GROUP_VERSION
    inputType: FreeText
    multiline: false
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    multiline: false
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
