name: kafka_to_feature_store
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: InputTopic
    multiline: false
    defaultValue: ohlc
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    multiline: false
    defaultValue: trade_to_ohlc_live6
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
