name: kafka_to_feature_store
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: InputTopic
    multiline: false
    defaultValue: ohlc
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    multiline: false
    defaultValue: trade_to_ohlc_live6
  - name: FEATURE_GROUP_NAME
    inputType: FreeText
    multiline: false
    defaultValue: ohlc_feature_group
  - name: FEATURE_GROUP_VERSION
    inputType: FreeText
    multiline: false
    defaultValue: 1
  - name: BUFFER_SIZE
    inputType: FreeText
    multiline: false
    defaultValue: 1440
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    multiline: false
    defaultValue: live
  - name: HOPSWORKS_PROJECT_NAME
    inputType: FreeText
    multiline: false
    defaultValue: testone
  - name: HOPSWORKS_API_KEY
    inputType: FreeText
    multiline: false
    defaultValue: jJ3EIJAs48fiyY7p.x6b3cmLBwWldeqRZRe0yLfPdCzwcvm9gyEow6jgLY7QbskO4nIov6JuZFsT7ndEp
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
